PE-796 Create Gluu Laravel Guard
DiagVN/gluu-php-sdk pull request #13
Opened 2022-12-13 16:40 UTC by buiminhducdiag

Ticket:
https://diag.atlassian.net/browse/PE-796

2022-12-13 17:20 UTC, toanauthe requested changes
I think we should separating this to something like 
```
class GluuGuard
{
  public function check()
  public function user()
  public function setUser()
  public function validate()
}
```
Then when you register the guard with laravel, we can use something like this
Auth::check()..
-> Then Other services no need to re-implement the authentication again, they just define the guard to gluu-guard

2022-12-13 17:37 UTC, buiminhducdiag commented
> I think we should separating this to something like
> 
> ```
> class GluuGuard
> {
>   public function check()
>   public function user()
>   public function setUser()
>   public function validate()
> }
> ```
> 
> Then when you register the guard with laravel, we can use something like this Auth::check().. -> Then Other services no need to re-implement the authentication again, they just define the guard to gluu-guard

2022-12-14 04:37 UTC, bradleynguyendiag commented on src/App/GluuGuard.php
> +            return $userRepository->allQuery(['username' => $result['username']])->first();
Can we do some caching here. it should not call to Gluu server every time even token still valid.

2022-12-14 06:25 UTC, buiminhducdiag commented on src/App/GluuGuard.php
> +            return $userRepository->allQuery(['username' => $result['username']])->first();
Well, technically we can add caching here, but why we should do it? Validating token has its meaning when we can validate its validation with Gluu server. If we cache, we must deal with the cache itself, and how long it should be cached. And please think about security, if there is some reason, we need to remove the token from Gluu, and we still cache the token and its validation, then what happens?

2022-12-14 06:28 UTC, bradleynguyendiag commented on src/App/GluuGuard.php
> +            return $userRepository->allQuery(['username' => $result['username']])->first();
That case never happen.

2022-12-14 07:50 UTC, toanauthe commented on src/Providers/GluuServiceProvider.php
>  use GuzzleHttp\Client;
use Illuminate\Support\Facades\Auth;

2022-12-14 07:51 UTC, bradleynguyendiag commented on src/App/GluuGuard.php
> +            Cache::put($this->request->bearerToken(), $result, now()->addHours(4));
Can we move 4 to config?

2022-12-14 14:57 UTC, bradleynguyendiag commented on src/Config/gluu.php
> +    'gluu_guard_cache_hour' => 4,
Pls set to use env

2022-12-15 07:14 UTC, bradleynguyendiag approved these changes

2022-12-15 14:12 UTC, buiminhducdiag commented
> I think we should separating this to something like
> 
> ```
> class GluuGuard
> {
>   public function check()
>   public function user()
>   public function setUser()
>   public function validate()
> }
> ```
> 
> Then when you register the guard with laravel, we can use something like this Auth::check().. -> Then Other services no need to re-implement the authentication again, they just define the guard to gluu-guard

Done

2022-12-15 14:13 UTC, buiminhducdiag commented
> I think we should separating this to something like
> 
> ```
> class GluuGuard
> {
>   public function check()
>   public function user()
>   public function setUser()
>   public function validate()
> }
> ```
> 
> Then when you register the guard with laravel, we can use something like this Auth::check().. -> Then Other services no need to re-implement the authentication again, they just define the guard to gluu-guard

Done

2022-12-15 14:17 UTC, toanauthe approved these changes

2022-12-15 14:17 UTC, merged